__title__ = "pyquizjp"
__description__ = "Python quiz module from recklessop"
__url__ = "https://github.com/recklessop/pyquizjp"
__version__ = "0.5.5"
__build__ = 0x023100
__author__ = "Justin Paul"
__author_email__ = "justin@jpaul.me"
__license__ = "GPL-3.0"
__copyright__ = "Copyright Justin Paul"
